#!/bin/bash

set -eo pipefail

if [[ -z $TANSIT_GPG_ENCRYPTED_SECRET_KEY_URL ]]; then
  echo "You must provide TANSIT_GPG_ENCRYPTED_SECRET_KEY_URL, to be used by 'aws s3 cp'"
  exit 1
fi

export GNUPGHOME=/dev/shm/gpghome
rm -r "$GNUPGHOME" || true
mkdir "$GNUPGHOME"

encrypted_key="/dev/shm/gpgsecret.key.enc"

aws s3 cp "$TANSIT_GPG_ENCRYPTED_SECRET_KEY_URL" "$encrypted_key"
echo "Importing key..."
aws kms decrypt --ciphertext-blob "fileb://${encrypted_key}" \
    --query Plaintext --output text | \
  base64 -d | \
  gpg --allow-secret-key-import --import -
rm "$encrypted_key"
echo "Done importing key. Starting tansit:"

exec tansit "$@"
